### ISSUE TITLE
TypeError trying to update project

### ISSUE THREAD

**Issue by eripa** [RisingOak/stashy#8]
Trying to update a project using project.update(). I'm not entirely sure what the 'project' argument is but I figured that it is either the id or the key. Neither works. Getting TypeError in both cases. Any idea?

```
project_id = self.connection.projects[MYKEY].get()['id']
new_description = 'testing adding description...'

Traceback (most recent call last):
  File "./stash.py", line 65, in <module>
    main()
  File "./stash.py", line 61, in main
    s.add_to_description('testing adding description...')
  File "./stash.py", line 54, in add_to_description
    self.connection.projects[MYKEY].update(project_id, description=new_description)
  File "<string>", line 2, in update
  File "build/bdist.linux-x86_64/egg/stashy/errors.py", line 53, in response_or_error
  File "build/bdist.linux-x86_64/egg/stashy/errors.py", line 35, in maybe_throw
  File "build/bdist.linux-x86_64/egg/stashy/errors.py", line 25, in __init__
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by tonytamsf** [comment]
please re-open if still needed.
